/*
Copyright 2015 The Kubernetes Authors All rights reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// DO NOT EDIT. THIS FILE IS AUTO-GENERATED BY $KUBEROOT/hack/update-generated-conversions.sh

package v1alpha1

import (
	reflect "reflect"

	api "k8s.io/kubernetes/pkg/api"
	componentconfig "k8s.io/kubernetes/pkg/apis/componentconfig"
	conversion "k8s.io/kubernetes/pkg/conversion"
)

func autoConvert_componentconfig_KubeProxyConfiguration_To_v1alpha1_KubeProxyConfiguration(in *componentconfig.KubeProxyConfiguration, out *KubeProxyConfiguration, s conversion.Scope) error {
	if defaulting, found := s.DefaultingInterface(reflect.TypeOf(*in)); found {
		defaulting.(func(*componentconfig.KubeProxyConfiguration))(in)
	}
	if err := api.Convert_unversioned_TypeMeta_To_unversioned_TypeMeta(&in.TypeMeta, &out.TypeMeta, s); err != nil {
		return err
	}
	out.BindAddress = in.BindAddress
	out.HealthzBindAddress = in.HealthzBindAddress
	out.HealthzPort = int32(in.HealthzPort)
	out.HostnameOverride = in.HostnameOverride
	if in.IPTablesMasqueradeBit != nil {
		out.IPTablesMasqueradeBit = new(int32)
		*out.IPTablesMasqueradeBit = int32(*in.IPTablesMasqueradeBit)
	} else {
		out.IPTablesMasqueradeBit = nil
	}
	if err := s.Convert(&in.IPTablesSyncPeriod, &out.IPTablesSyncPeriod, 0); err != nil {
		return err
	}
	out.KubeconfigPath = in.KubeconfigPath
	out.MasqueradeAll = in.MasqueradeAll
	out.Master = in.Master
	if in.OOMScoreAdj != nil {
		out.OOMScoreAdj = new(int32)
		*out.OOMScoreAdj = int32(*in.OOMScoreAdj)
	} else {
		out.OOMScoreAdj = nil
	}
	out.Mode = ProxyMode(in.Mode)
	out.PortRange = in.PortRange
	out.ResourceContainer = in.ResourceContainer
	if err := s.Convert(&in.UDPIdleTimeout, &out.UDPIdleTimeout, 0); err != nil {
		return err
	}
	out.ConntrackMax = int32(in.ConntrackMax)
	if err := s.Convert(&in.ConntrackTCPEstablishedTimeout, &out.ConntrackTCPEstablishedTimeout, 0); err != nil {
		return err
	}
	return nil
}

func Convert_componentconfig_KubeProxyConfiguration_To_v1alpha1_KubeProxyConfiguration(in *componentconfig.KubeProxyConfiguration, out *KubeProxyConfiguration, s conversion.Scope) error {
	return autoConvert_componentconfig_KubeProxyConfiguration_To_v1alpha1_KubeProxyConfiguration(in, out, s)
}

func autoConvert_componentconfig_KubeSchedulerConfiguration_To_v1alpha1_KubeSchedulerConfiguration(in *componentconfig.KubeSchedulerConfiguration, out *KubeSchedulerConfiguration, s conversion.Scope) error {
	if defaulting, found := s.DefaultingInterface(reflect.TypeOf(*in)); found {
		defaulting.(func(*componentconfig.KubeSchedulerConfiguration))(in)
	}
	if err := api.Convert_unversioned_TypeMeta_To_unversioned_TypeMeta(&in.TypeMeta, &out.TypeMeta, s); err != nil {
		return err
	}
	out.Port = in.Port
	out.Address = in.Address
	out.AlgorithmProvider = in.AlgorithmProvider
	out.PolicyConfigFile = in.PolicyConfigFile
	if err := api.Convert_bool_To_bool_ref(&in.EnableProfiling, &out.EnableProfiling, s); err != nil {
		return err
	}
	out.KubeAPIQPS = in.KubeAPIQPS
	out.KubeAPIBurst = in.KubeAPIBurst
	out.SchedulerName = in.SchedulerName
	if err := Convert_componentconfig_LeaderElectionConfiguration_To_v1alpha1_LeaderElectionConfiguration(&in.LeaderElection, &out.LeaderElection, s); err != nil {
		return err
	}
	return nil
}

func Convert_componentconfig_KubeSchedulerConfiguration_To_v1alpha1_KubeSchedulerConfiguration(in *componentconfig.KubeSchedulerConfiguration, out *KubeSchedulerConfiguration, s conversion.Scope) error {
	return autoConvert_componentconfig_KubeSchedulerConfiguration_To_v1alpha1_KubeSchedulerConfiguration(in, out, s)
}

func autoConvert_componentconfig_KubeletConfiguration_To_v1alpha1_KubeletConfiguration(in *componentconfig.KubeletConfiguration, out *KubeletConfiguration, s conversion.Scope) error {
	if defaulting, found := s.DefaultingInterface(reflect.TypeOf(*in)); found {
		defaulting.(func(*componentconfig.KubeletConfiguration))(in)
	}
	if err := api.Convert_unversioned_TypeMeta_To_unversioned_TypeMeta(&in.TypeMeta, &out.TypeMeta, s); err != nil {
		return err
	}
	out.Config = in.Config
	if err := s.Convert(&in.SyncFrequency, &out.SyncFrequency, 0); err != nil {
		return err
	}
	if err := s.Convert(&in.FileCheckFrequency, &out.FileCheckFrequency, 0); err != nil {
		return err
	}
	if err := s.Convert(&in.HTTPCheckFrequency, &out.HTTPCheckFrequency, 0); err != nil {
		return err
	}
	out.ManifestURL = in.ManifestURL
	out.ManifestURLHeader = in.ManifestURLHeader
	if err := api.Convert_bool_To_bool_ref(&in.EnableServer, &out.EnableServer, s); err != nil {
		return err
	}
	out.Address = in.Address
	out.Port = int32(in.Port)
	out.ReadOnlyPort = int32(in.ReadOnlyPort)
	out.TLSCertFile = in.TLSCertFile
	out.TLSPrivateKeyFile = in.TLSPrivateKeyFile
	out.CertDirectory = in.CertDirectory
	out.HostnameOverride = in.HostnameOverride
	out.PodInfraContainerImage = in.PodInfraContainerImage
	out.DockerEndpoint = in.DockerEndpoint
	out.RootDirectory = in.RootDirectory
	if err := api.Convert_bool_To_bool_ref(&in.AllowPrivileged, &out.AllowPrivileged, s); err != nil {
		return err
	}
	if in.HostNetworkSources != nil {
		out.HostNetworkSources = make([]string, len(in.HostNetworkSources))
		for i := range in.HostNetworkSources {
			out.HostNetworkSources[i] = in.HostNetworkSources[i]
		}
	} else {
		out.HostNetworkSources = nil
	}
	if in.HostPIDSources != nil {
		out.HostPIDSources = make([]string, len(in.HostPIDSources))
		for i := range in.HostPIDSources {
			out.HostPIDSources[i] = in.HostPIDSources[i]
		}
	} else {
		out.HostPIDSources = nil
	}
	if in.HostIPCSources != nil {
		out.HostIPCSources = make([]string, len(in.HostIPCSources))
		for i := range in.HostIPCSources {
			out.HostIPCSources[i] = in.HostIPCSources[i]
		}
	} else {
		out.HostIPCSources = nil
	}
	out.RegistryPullQPS = in.RegistryPullQPS
	out.RegistryBurst = int64(in.RegistryBurst)
	out.EventRecordQPS = in.EventRecordQPS
	out.EventBurst = int64(in.EventBurst)
	if err := api.Convert_bool_To_bool_ref(&in.EnableDebuggingHandlers, &out.EnableDebuggingHandlers, s); err != nil {
		return err
	}
	if err := s.Convert(&in.MinimumGCAge, &out.MinimumGCAge, 0); err != nil {
		return err
	}
	out.MaxPerPodContainerCount = int64(in.MaxPerPodContainerCount)
	if err := api.Convert_int_To_int64_ref(&in.MaxContainerCount, &out.MaxContainerCount, s); err != nil {
		return err
	}
	out.CAdvisorPort = int32(in.CAdvisorPort)
	out.HealthzPort = int32(in.HealthzPort)
	out.HealthzBindAddress = in.HealthzBindAddress
	out.OOMScoreAdj = int32(in.OOMScoreAdj)
	if err := api.Convert_bool_To_bool_ref(&in.RegisterNode, &out.RegisterNode, s); err != nil {
		return err
	}
	out.ClusterDomain = in.ClusterDomain
	out.MasterServiceNamespace = in.MasterServiceNamespace
	out.ClusterDNS = in.ClusterDNS
	if err := s.Convert(&in.StreamingConnectionIdleTimeout, &out.StreamingConnectionIdleTimeout, 0); err != nil {
		return err
	}
	if err := s.Convert(&in.NodeStatusUpdateFrequency, &out.NodeStatusUpdateFrequency, 0); err != nil {
		return err
	}
	out.ImageGCHighThresholdPercent = int32(in.ImageGCHighThresholdPercent)
	out.ImageGCLowThresholdPercent = int32(in.ImageGCLowThresholdPercent)
	out.LowDiskSpaceThresholdMB = int64(in.LowDiskSpaceThresholdMB)
	if err := s.Convert(&in.VolumeStatsAggPeriod, &out.VolumeStatsAggPeriod, 0); err != nil {
		return err
	}
	out.NetworkPluginName = in.NetworkPluginName
	out.NetworkPluginDir = in.NetworkPluginDir
	out.VolumePluginDir = in.VolumePluginDir
	out.CloudProvider = in.CloudProvider
	out.CloudConfigFile = in.CloudConfigFile
	out.KubeletCgroups = in.KubeletCgroups
	out.RuntimeCgroups = in.RuntimeCgroups
	out.SystemCgroups = in.SystemCgroups
	out.CgroupRoot = in.CgroupRoot
	out.ContainerRuntime = in.ContainerRuntime
	out.RktPath = in.RktPath
	if err := api.Convert_string_To_string_ref(&in.LockFilePath, &out.LockFilePath, s); err != nil {
		return err
	}
	out.RktStage1Image = in.RktStage1Image
	if err := api.Convert_bool_To_bool_ref(&in.ConfigureCBR0, &out.ConfigureCBR0, s); err != nil {
		return err
	}
	if err := api.Convert_bool_To_bool_ref(&in.HairpinMode, &out.HairpinMode, s); err != nil {
		return err
	}
	out.MaxPods = int32(in.MaxPods)
	out.DockerExecHandlerName = in.DockerExecHandlerName
	out.PodCIDR = in.PodCIDR
	out.ResolverConfig = in.ResolverConfig
	if err := api.Convert_bool_To_bool_ref(&in.CPUCFSQuota, &out.CPUCFSQuota, s); err != nil {
		return err
	}
	if err := api.Convert_bool_To_bool_ref(&in.Containerized, &out.Containerized, s); err != nil {
		return err
	}
	out.MaxOpenFiles = in.MaxOpenFiles
	if err := api.Convert_bool_To_bool_ref(&in.ReconcileCIDR, &out.ReconcileCIDR, s); err != nil {
		return err
	}
	if err := api.Convert_bool_To_bool_ref(&in.RegisterSchedulable, &out.RegisterSchedulable, s); err != nil {
		return err
	}
	out.KubeAPIQPS = in.KubeAPIQPS
	out.KubeAPIBurst = int32(in.KubeAPIBurst)
	if err := api.Convert_bool_To_bool_ref(&in.SerializeImagePulls, &out.SerializeImagePulls, s); err != nil {
		return err
	}
	if err := api.Convert_bool_To_bool_ref(&in.ExperimentalFlannelOverlay, &out.ExperimentalFlannelOverlay, s); err != nil {
		return err
	}
	if err := s.Convert(&in.OutOfDiskTransitionFrequency, &out.OutOfDiskTransitionFrequency, 0); err != nil {
		return err
	}
	out.NodeIP = in.NodeIP
	if in.NodeLabels != nil {
		out.NodeLabels = make(map[string]string)
		for key, val := range in.NodeLabels {
			out.NodeLabels[key] = val
		}
	} else {
		out.NodeLabels = nil
	}
	out.NonMasqueradeCIDR = in.NonMasqueradeCIDR
	out.EnableCustomMetrics = in.EnableCustomMetrics
	return nil
}

func Convert_componentconfig_KubeletConfiguration_To_v1alpha1_KubeletConfiguration(in *componentconfig.KubeletConfiguration, out *KubeletConfiguration, s conversion.Scope) error {
	return autoConvert_componentconfig_KubeletConfiguration_To_v1alpha1_KubeletConfiguration(in, out, s)
}

func autoConvert_componentconfig_LeaderElectionConfiguration_To_v1alpha1_LeaderElectionConfiguration(in *componentconfig.LeaderElectionConfiguration, out *LeaderElectionConfiguration, s conversion.Scope) error {
	if defaulting, found := s.DefaultingInterface(reflect.TypeOf(*in)); found {
		defaulting.(func(*componentconfig.LeaderElectionConfiguration))(in)
	}
	if err := api.Convert_bool_To_bool_ref(&in.LeaderElect, &out.LeaderElect, s); err != nil {
		return err
	}
	if err := s.Convert(&in.LeaseDuration, &out.LeaseDuration, 0); err != nil {
		return err
	}
	if err := s.Convert(&in.RenewDeadline, &out.RenewDeadline, 0); err != nil {
		return err
	}
	if err := s.Convert(&in.RetryPeriod, &out.RetryPeriod, 0); err != nil {
		return err
	}
	return nil
}

func Convert_componentconfig_LeaderElectionConfiguration_To_v1alpha1_LeaderElectionConfiguration(in *componentconfig.LeaderElectionConfiguration, out *LeaderElectionConfiguration, s conversion.Scope) error {
	return autoConvert_componentconfig_LeaderElectionConfiguration_To_v1alpha1_LeaderElectionConfiguration(in, out, s)
}

func autoConvert_v1alpha1_KubeProxyConfiguration_To_componentconfig_KubeProxyConfiguration(in *KubeProxyConfiguration, out *componentconfig.KubeProxyConfiguration, s conversion.Scope) error {
	if defaulting, found := s.DefaultingInterface(reflect.TypeOf(*in)); found {
		defaulting.(func(*KubeProxyConfiguration))(in)
	}
	if err := api.Convert_unversioned_TypeMeta_To_unversioned_TypeMeta(&in.TypeMeta, &out.TypeMeta, s); err != nil {
		return err
	}
	out.BindAddress = in.BindAddress
	out.HealthzBindAddress = in.HealthzBindAddress
	out.HealthzPort = int(in.HealthzPort)
	out.HostnameOverride = in.HostnameOverride
	if in.IPTablesMasqueradeBit != nil {
		out.IPTablesMasqueradeBit = new(int)
		*out.IPTablesMasqueradeBit = int(*in.IPTablesMasqueradeBit)
	} else {
		out.IPTablesMasqueradeBit = nil
	}
	if err := s.Convert(&in.IPTablesSyncPeriod, &out.IPTablesSyncPeriod, 0); err != nil {
		return err
	}
	out.KubeconfigPath = in.KubeconfigPath
	out.MasqueradeAll = in.MasqueradeAll
	out.Master = in.Master
	if in.OOMScoreAdj != nil {
		out.OOMScoreAdj = new(int)
		*out.OOMScoreAdj = int(*in.OOMScoreAdj)
	} else {
		out.OOMScoreAdj = nil
	}
	out.Mode = componentconfig.ProxyMode(in.Mode)
	out.PortRange = in.PortRange
	out.ResourceContainer = in.ResourceContainer
	if err := s.Convert(&in.UDPIdleTimeout, &out.UDPIdleTimeout, 0); err != nil {
		return err
	}
	out.ConntrackMax = int(in.ConntrackMax)
	if err := s.Convert(&in.ConntrackTCPEstablishedTimeout, &out.ConntrackTCPEstablishedTimeout, 0); err != nil {
		return err
	}
	return nil
}

func Convert_v1alpha1_KubeProxyConfiguration_To_componentconfig_KubeProxyConfiguration(in *KubeProxyConfiguration, out *componentconfig.KubeProxyConfiguration, s conversion.Scope) error {
	return autoConvert_v1alpha1_KubeProxyConfiguration_To_componentconfig_KubeProxyConfiguration(in, out, s)
}

func autoConvert_v1alpha1_KubeSchedulerConfiguration_To_componentconfig_KubeSchedulerConfiguration(in *KubeSchedulerConfiguration, out *componentconfig.KubeSchedulerConfiguration, s conversion.Scope) error {
	if defaulting, found := s.DefaultingInterface(reflect.TypeOf(*in)); found {
		defaulting.(func(*KubeSchedulerConfiguration))(in)
	}
	if err := api.Convert_unversioned_TypeMeta_To_unversioned_TypeMeta(&in.TypeMeta, &out.TypeMeta, s); err != nil {
		return err
	}
	out.Port = in.Port
	out.Address = in.Address
	out.AlgorithmProvider = in.AlgorithmProvider
	out.PolicyConfigFile = in.PolicyConfigFile
	if err := api.Convert_bool_ref_To_bool(&in.EnableProfiling, &out.EnableProfiling, s); err != nil {
		return err
	}
	out.KubeAPIQPS = in.KubeAPIQPS
	out.KubeAPIBurst = in.KubeAPIBurst
	out.SchedulerName = in.SchedulerName
	if err := Convert_v1alpha1_LeaderElectionConfiguration_To_componentconfig_LeaderElectionConfiguration(&in.LeaderElection, &out.LeaderElection, s); err != nil {
		return err
	}
	return nil
}

func Convert_v1alpha1_KubeSchedulerConfiguration_To_componentconfig_KubeSchedulerConfiguration(in *KubeSchedulerConfiguration, out *componentconfig.KubeSchedulerConfiguration, s conversion.Scope) error {
	return autoConvert_v1alpha1_KubeSchedulerConfiguration_To_componentconfig_KubeSchedulerConfiguration(in, out, s)
}

func autoConvert_v1alpha1_KubeletConfiguration_To_componentconfig_KubeletConfiguration(in *KubeletConfiguration, out *componentconfig.KubeletConfiguration, s conversion.Scope) error {
	if defaulting, found := s.DefaultingInterface(reflect.TypeOf(*in)); found {
		defaulting.(func(*KubeletConfiguration))(in)
	}
	if err := api.Convert_unversioned_TypeMeta_To_unversioned_TypeMeta(&in.TypeMeta, &out.TypeMeta, s); err != nil {
		return err
	}
	out.Config = in.Config
	if err := s.Convert(&in.SyncFrequency, &out.SyncFrequency, 0); err != nil {
		return err
	}
	if err := s.Convert(&in.FileCheckFrequency, &out.FileCheckFrequency, 0); err != nil {
		return err
	}
	if err := s.Convert(&in.HTTPCheckFrequency, &out.HTTPCheckFrequency, 0); err != nil {
		return err
	}
	out.ManifestURL = in.ManifestURL
	out.ManifestURLHeader = in.ManifestURLHeader
	if err := api.Convert_bool_ref_To_bool(&in.EnableServer, &out.EnableServer, s); err != nil {
		return err
	}
	out.Address = in.Address
	out.Port = int(in.Port)
	out.ReadOnlyPort = int(in.ReadOnlyPort)
	out.TLSCertFile = in.TLSCertFile
	out.TLSPrivateKeyFile = in.TLSPrivateKeyFile
	out.CertDirectory = in.CertDirectory
	out.HostnameOverride = in.HostnameOverride
	out.PodInfraContainerImage = in.PodInfraContainerImage
	out.DockerEndpoint = in.DockerEndpoint
	out.RootDirectory = in.RootDirectory
	if err := api.Convert_bool_ref_To_bool(&in.AllowPrivileged, &out.AllowPrivileged, s); err != nil {
		return err
	}
	if in.HostNetworkSources != nil {
		out.HostNetworkSources = make([]string, len(in.HostNetworkSources))
		for i := range in.HostNetworkSources {
			out.HostNetworkSources[i] = in.HostNetworkSources[i]
		}
	} else {
		out.HostNetworkSources = nil
	}
	if in.HostPIDSources != nil {
		out.HostPIDSources = make([]string, len(in.HostPIDSources))
		for i := range in.HostPIDSources {
			out.HostPIDSources[i] = in.HostPIDSources[i]
		}
	} else {
		out.HostPIDSources = nil
	}
	if in.HostIPCSources != nil {
		out.HostIPCSources = make([]string, len(in.HostIPCSources))
		for i := range in.HostIPCSources {
			out.HostIPCSources[i] = in.HostIPCSources[i]
		}
	} else {
		out.HostIPCSources = nil
	}
	out.RegistryPullQPS = in.RegistryPullQPS
	out.RegistryBurst = int(in.RegistryBurst)
	out.EventRecordQPS = in.EventRecordQPS
	out.EventBurst = int(in.EventBurst)
	if err := api.Convert_bool_ref_To_bool(&in.EnableDebuggingHandlers, &out.EnableDebuggingHandlers, s); err != nil {
		return err
	}
	if err := s.Convert(&in.MinimumGCAge, &out.MinimumGCAge, 0); err != nil {
		return err
	}
	out.MaxPerPodContainerCount = int(in.MaxPerPodContainerCount)
	if err := api.Convert_int64_ref_To_int(&in.MaxContainerCount, &out.MaxContainerCount, s); err != nil {
		return err
	}
	out.CAdvisorPort = int(in.CAdvisorPort)
	out.HealthzPort = int(in.HealthzPort)
	out.HealthzBindAddress = in.HealthzBindAddress
	out.OOMScoreAdj = int(in.OOMScoreAdj)
	if err := api.Convert_bool_ref_To_bool(&in.RegisterNode, &out.RegisterNode, s); err != nil {
		return err
	}
	out.ClusterDomain = in.ClusterDomain
	out.MasterServiceNamespace = in.MasterServiceNamespace
	out.ClusterDNS = in.ClusterDNS
	if err := s.Convert(&in.StreamingConnectionIdleTimeout, &out.StreamingConnectionIdleTimeout, 0); err != nil {
		return err
	}
	if err := s.Convert(&in.NodeStatusUpdateFrequency, &out.NodeStatusUpdateFrequency, 0); err != nil {
		return err
	}
	out.ImageGCHighThresholdPercent = int(in.ImageGCHighThresholdPercent)
	out.ImageGCLowThresholdPercent = int(in.ImageGCLowThresholdPercent)
	out.LowDiskSpaceThresholdMB = int(in.LowDiskSpaceThresholdMB)
	if err := s.Convert(&in.VolumeStatsAggPeriod, &out.VolumeStatsAggPeriod, 0); err != nil {
		return err
	}
	out.NetworkPluginName = in.NetworkPluginName
	out.NetworkPluginDir = in.NetworkPluginDir
	out.VolumePluginDir = in.VolumePluginDir
	out.CloudProvider = in.CloudProvider
	out.CloudConfigFile = in.CloudConfigFile
	out.KubeletCgroups = in.KubeletCgroups
	out.RuntimeCgroups = in.RuntimeCgroups
	out.SystemCgroups = in.SystemCgroups
	out.CgroupRoot = in.CgroupRoot
	out.ContainerRuntime = in.ContainerRuntime
	out.RktPath = in.RktPath
	if err := api.Convert_string_ref_To_string(&in.LockFilePath, &out.LockFilePath, s); err != nil {
		return err
	}
	out.RktStage1Image = in.RktStage1Image
	if err := api.Convert_bool_ref_To_bool(&in.ConfigureCBR0, &out.ConfigureCBR0, s); err != nil {
		return err
	}
	if err := api.Convert_bool_ref_To_bool(&in.HairpinMode, &out.HairpinMode, s); err != nil {
		return err
	}
	out.MaxPods = int(in.MaxPods)
	out.DockerExecHandlerName = in.DockerExecHandlerName
	out.PodCIDR = in.PodCIDR
	out.ResolverConfig = in.ResolverConfig
	if err := api.Convert_bool_ref_To_bool(&in.CPUCFSQuota, &out.CPUCFSQuota, s); err != nil {
		return err
	}
	if err := api.Convert_bool_ref_To_bool(&in.Containerized, &out.Containerized, s); err != nil {
		return err
	}
	out.MaxOpenFiles = in.MaxOpenFiles
	if err := api.Convert_bool_ref_To_bool(&in.ReconcileCIDR, &out.ReconcileCIDR, s); err != nil {
		return err
	}
	if err := api.Convert_bool_ref_To_bool(&in.RegisterSchedulable, &out.RegisterSchedulable, s); err != nil {
		return err
	}
	out.KubeAPIQPS = in.KubeAPIQPS
	out.KubeAPIBurst = int(in.KubeAPIBurst)
	if err := api.Convert_bool_ref_To_bool(&in.SerializeImagePulls, &out.SerializeImagePulls, s); err != nil {
		return err
	}
	if err := api.Convert_bool_ref_To_bool(&in.ExperimentalFlannelOverlay, &out.ExperimentalFlannelOverlay, s); err != nil {
		return err
	}
	if err := s.Convert(&in.OutOfDiskTransitionFrequency, &out.OutOfDiskTransitionFrequency, 0); err != nil {
		return err
	}
	out.NodeIP = in.NodeIP
	if in.NodeLabels != nil {
		out.NodeLabels = make(map[string]string)
		for key, val := range in.NodeLabels {
			out.NodeLabels[key] = val
		}
	} else {
		out.NodeLabels = nil
	}
	out.NonMasqueradeCIDR = in.NonMasqueradeCIDR
	out.EnableCustomMetrics = in.EnableCustomMetrics
	return nil
}

func Convert_v1alpha1_KubeletConfiguration_To_componentconfig_KubeletConfiguration(in *KubeletConfiguration, out *componentconfig.KubeletConfiguration, s conversion.Scope) error {
	return autoConvert_v1alpha1_KubeletConfiguration_To_componentconfig_KubeletConfiguration(in, out, s)
}

func autoConvert_v1alpha1_LeaderElectionConfiguration_To_componentconfig_LeaderElectionConfiguration(in *LeaderElectionConfiguration, out *componentconfig.LeaderElectionConfiguration, s conversion.Scope) error {
	if defaulting, found := s.DefaultingInterface(reflect.TypeOf(*in)); found {
		defaulting.(func(*LeaderElectionConfiguration))(in)
	}
	if err := api.Convert_bool_ref_To_bool(&in.LeaderElect, &out.LeaderElect, s); err != nil {
		return err
	}
	if err := s.Convert(&in.LeaseDuration, &out.LeaseDuration, 0); err != nil {
		return err
	}
	if err := s.Convert(&in.RenewDeadline, &out.RenewDeadline, 0); err != nil {
		return err
	}
	if err := s.Convert(&in.RetryPeriod, &out.RetryPeriod, 0); err != nil {
		return err
	}
	return nil
}

func Convert_v1alpha1_LeaderElectionConfiguration_To_componentconfig_LeaderElectionConfiguration(in *LeaderElectionConfiguration, out *componentconfig.LeaderElectionConfiguration, s conversion.Scope) error {
	return autoConvert_v1alpha1_LeaderElectionConfiguration_To_componentconfig_LeaderElectionConfiguration(in, out, s)
}

func init() {
	err := api.Scheme.AddGeneratedConversionFuncs(
		autoConvert_componentconfig_KubeProxyConfiguration_To_v1alpha1_KubeProxyConfiguration,
		autoConvert_componentconfig_KubeSchedulerConfiguration_To_v1alpha1_KubeSchedulerConfiguration,
		autoConvert_componentconfig_KubeletConfiguration_To_v1alpha1_KubeletConfiguration,
		autoConvert_componentconfig_LeaderElectionConfiguration_To_v1alpha1_LeaderElectionConfiguration,
		autoConvert_v1alpha1_KubeProxyConfiguration_To_componentconfig_KubeProxyConfiguration,
		autoConvert_v1alpha1_KubeSchedulerConfiguration_To_componentconfig_KubeSchedulerConfiguration,
		autoConvert_v1alpha1_KubeletConfiguration_To_componentconfig_KubeletConfiguration,
		autoConvert_v1alpha1_LeaderElectionConfiguration_To_componentconfig_LeaderElectionConfiguration,
	)
	if err != nil {
		// If one of the conversion functions is malformed, detect it immediately.
		panic(err)
	}
}
