apiVersion: v1
kind: Pod
metadata:
  name: kube-addon-manager
  namespace: kube-system
  version: v1
spec:
  hostNetwork: true
  containers:
  - name: kube-addon-manager
    image: gcr.io/google_containers/kube-addon-manager:v1
    volumeMounts:
    - mountPath: /etc/kubernetes/
      name: addons
      readOnly: true
  volumes:
  - hostPath:
      path: /etc/kubernetes/
    name: addons
